### ISSUE TITLE
Create a rsmt2d.Tree interface wrapper for NamespacedMerkleTree

### ISSUE THREAD

**Issue by evan-forbes** [lazyledger/nmt#24]
We need a wrapper that fulfills the `rsmt2d.Tree` interface. That wrapper will need to be able to create nmt roots assuming that the namespaces are included in the data being pushed, but only for the first half of the tree. This means the wrapper should be aware of the square size ahead of time. 

[realted ll-core issue](https://github.com/lazyledger/lazyledger-core/issues/172)

**Comment by liamsi** [comment]
That wrapper doesn't necessarily need to live in this repo, right? It could be in ll-core for instance.

> This means the wrapper should be aware of the square size ahead of time.

Another way to achieve the same could be to let ll-core prefix everything with namespace ID, even the parity bytes. Then the tree can differentiate between real shares and (second half) parity shares because the latter would carry the max. namespace.

**Comment by evan-forbes** [comment]
I don't think it will be difficult to move the logic over to lazyledger-core, and it makes a lot of sense to keep all lazyledger-core logic in lazyledger-core, so I'll close this issue along with the PR.
